- name: Create Network Restore Play
  hosts: all
  gather_facts: false
  vars:
    data_store:
      scm:
        origin:
          user:
            name: "leogallego"
            email: "993814+leogallego@users.noreply.github.com" 
          url: "https://github.com/leogallego/nvc_use_cases.git"
          token: "{{ lookup('env', 'gh_token') }}"
          path: "data/backups/{{ ansible_date_time.date }}/{{ inventory_hostname }}"
          filename: "{{ ansible_date_time.date }}_{{ inventory_hostname }}.txt"
  tasks:
    - name: Set host-level var (for AAP compatibility)
      set_fact:
        data_store: "{{ data_store }}"
    - name: Restore network config from saved config
      ansible.builtin.include_role:
        name: network.backup.restore
      
              
