- name: Create Network Backup Play
  hosts: network
  tasks:
    - name: Create Network Backup
      ansible.builtin.include_role:
        name: network.backup.backup
      vars:
        operation: backup
        data_store:
          scm:
            origin:
              user:
                name: "leogallego"
                email: "993814+leogallego@users.noreply.github.com" 
              url: "https://github.com/leogallego/aap-network-report.git"
              token: "{{ TOKEN }}"
              path: "rtr1.txt"
