- name: Persist Network Reports
  hosts: network
  tasks:
    - name: Invoke persist role
      ansible.builtin.include_role:
        name: network.reports.persist
      vars:
        format: json
        resources:
          - interfaces
          - l3_interfaces
          - l2_interfaces
        data_store:
          scm:
            parent_directory: "/home/rhel"
            origin:
              user:
                name: "leogallego"
                email: "993814+leogallego@users.noreply.github.com" 
              url: "https://github.com/leogallego/nvc_use_cases.git"
              token: "{{ TOKEN }}"
